/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Sonti24.c                                             *
* Font:        宋体                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\font24.txt       *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSonti24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSonti24_5723[ 72] = { /* code 5723 */
  ________,________,________,
  ________,________,________,
  ________,________,XX______,
  _____XXX,XXXXXXXX,XXX_____,
  _______X,_______X,X_______,
  ________,X______X,X_______,
  ________,_X____XX,________,
  ________,__XX_XX_,________,
  ________,___XXX__,________,
  ________,___XXXX_,________,
  ________,_XX___XX,XX______,
  _______X,X___X___,XXXXXX__,
  _____XX_,____X___,___XX___,
  _XXXX___,____X___,________,
  ________,____X___,________,
  ________,____X___,__XX____,
  ____XXXX,XXXXXXXX,XX______,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,____XX__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSonti24_5B5D[ 72] = { /* code 5B5D */
  ________,________,________,
  ________,________,________,
  ________,__XX____,_X______,
  ________,__X_____,_XX_____,
  ________,__X__XX_,XX______,
  _____XXX,XXXXX__X,X_______,
  ________,__X____X,________,
  ________,__X___X_,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,____X___,________,
  ________,___X____,________,
  ________,_XX_____,X_______,
  ____XXXX,XX_XXXXX,XX______,
  _______X,______X_,________,
  _____XX_,___XXX__,________,
  ___XX___,___XX___,________,
  __X_____,___XX___,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,XXXX____,________,
  ________,__XX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSonti24_9EC4[ 72] = { /* code 9EC4 */
  ________,________,________,
  ________,X_____X_,________,
  ________,XX_____X,________,
  ________,X______X,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,____XX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XX___,________,
  _____X__,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,___XX___,__X_____,
  _____X__,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,___XX___,__X_____,
  _____X__,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,X____X__,________,
  _______X,XXX___XX,X_______,
  ______XX,________,_XXX____,
  _____X__,________,__XXX___,
  ___XX___,________,___XX___,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSonti24_CharInfo[3] = {
   {  24,  24,  3, acGUI_FontSonti24_5723 } /* code 5723 */
  ,{  24,  24,  3, acGUI_FontSonti24_5B5D } /* code 5B5D */
  ,{  24,  24,  3, acGUI_FontSonti24_9EC4 } /* code 9EC4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSonti24_Prop3 = {
   0x9EC4 /* first character */
  ,0x9EC4 /* last character  */
  ,&GUI_FontSonti24_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSonti24_Prop2 = {
   0x5B5D /* first character */
  ,0x5B5D /* last character  */
  ,&GUI_FontSonti24_CharInfo[  1] /* address of first character */
  ,&GUI_FontSonti24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSonti24_Prop1 = {
   0x5723 /* first character */
  ,0x5723 /* last character  */
  ,&GUI_FontSonti24_CharInfo[  0] /* address of first character */
  ,&GUI_FontSonti24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSonti24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSonti24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

